 [build]
   base = "dashboard"
   command = "yarn build"
   publish = ".next"

   [build.environment]
     # URL Railway del backend deployato
     API_URL = "https://pitlane-production.up.railway.app"
     NEXT_PUBLIC_LIVE_URL = "https://pitlane-production.up.railway.app"
     SKIP_ENV_VALIDATION = "1"

 [[plugins]]
   package = "@netlify/plugin-nextjs"
