 [build]
   base = "dashboard"
   command = "yarn build"
   publish = ".next"

   [build.environment]
     # Abilita il simulator mode per dimostrazione
     # In produzione, sostituisci con gli URL reali dei tuoi servizi backend
     API_URL = "https://example.com"
     NEXT_PUBLIC_LIVE_URL = "https://example.com"
     SKIP_ENV_VALIDATION = "1"

 [[plugins]]
   package = "@netlify/plugin-nextjs"
